site_name: aric6494's notes
nav:
  - 介绍: index.md
  - Termux:
      - Termux/termux.md 
  - Manim:
      - Manim/三角函数.md
  - 数字工具: 数字工具.md

theme:
  name: material
  features:
    - content.code.copy

extra_css:
  - stylesheets/extra.css