site_name: aric6494's notes
nav:
  - 介绍: index.md
  - 英语:
      - 语法:
          - 动词: english/grammar/动词.md
  - Termux:
      - Termux/termux.md 

theme: material

extra_css:
  - stylesheets/extra.css